Added "get_serial_number" Feature
stevemarple/python-zwoasi pull request #30
Opened 2024-11-05 20:44 UTC by kblu

Added python support for the "zwolib.ASIGetSerialNumber" method.  This feature distinguishes between multiple cameras of the same model type when they are connected on the same platform.  The feature has been tested using two ASI6200MM Pro cameras.  The resulting serial numbers were found to be identical to the serial numbers returned by the ASIImg application. 

[Please excuse if this is a duplicate pull request.]

2025-02-26 23:02 UTC, iromero91 requested changes
Sorry for the much delayed review. If you're interested in amending the commit you can do so otherwise i can test and merge this sans the hunk that changes the version number.

2025-02-26 23:02 UTC, iromero91 commented on zwoasi/__init__.py
> +__version__ = '0.2.1'
Please dont change the version in a feature commit

2025-02-27 00:30 UTC, kblu commented
Thank you!  I pushed the requested version change.

2025-02-27 01:30 UTC, merged

2025-02-27 01:31 UTC, iromero91 commented
Thanks for the quick fix, change has been merged to master. I'll do a pypi release after i merge a couple more things